---
- hosts: localhost
  connection: local
  become: true
  vars:
  tasks:
    - name: Updating APK Cache
      apk:
        update_cache: yes

    - name: Installing Pre-Reqs
      apk:
        name: "{{ item }}"
        state: "present"
      with_items:
        - 'rsyslog'
        - 'supervisor'

    - name: Installing Redis
      apk:
        name: "redis"
        state: "present"

    - name: Ensuring /data Exists
      file:
        path: "/data"
        owner: "redis"
        group: "redis"
        state: "directory"

    - name: Configuring Redis
      replace:
        dest: "/etc/redis.conf"
        regexp: "^{{ item.regex }}"
        replace: "{{ item.replace }}"
      with_items:
        - regex: 'daemonize yes'
          replace: 'daemonize no'
        - regex: 'bind 127.0.0.1'
          replace: 'bind 0.0.0.0'
