---
- hosts: localhost
  connection: local
  become: true
  vars:
    - gosu_ver: '1.9'
  tasks:
    - name: Installing apt-transport-https
      apt:
        name: "apt-transport-https"
        state: "present"

    - name: Installing ca-certificates
      apt:
        name: "ca-certificates"
        state: "latest"

    - name: Installing dumb-init
      apt:
        deb: "https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64.deb"

    - name: Installing gosu
      get_url:
        url: "https://github.com/tianon/gosu/releases/download/{{ gosu_ver }}/gosu-amd64"
        dest: "/usr/local/bin/gosu"
        mode: 0755

    - name: Adding Redis PPA
      apt_repository:
        repo: "ppa:chris-lea/redis-server"
        state: "present"

    - name: Installing Redis
      apt:
        name: "redis-server"
        state: "present"
        install_recommends: no

    - name: Ensuring /data Exists
      file:
        path: "/data"
        owner: "redis"
        group: "redis"
        state: "directory"

    - name: Configuring Redis
      replace:
        dest: "/etc/redis/redis.conf"
        regexp: "^{{ item.regex }}"
        replace: "{{ item.replace }}"
      with_items:
        - regex: 'daemonize yes'
          replace: 'daemonize no'
        - regex: 'bind 127.0.0.1'
          replace: 'bind 0.0.0.0'
